language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-19mode
  - rbx
  - 2.0.0
gemfile:
  - gemfiles/activesupport_3_2.gemfile
  - gemfiles/activesupport_4_0.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/activesupport_4_0.gemfile
